import RegisterForm from '@/components/register/registerForm';
import React from 'react'

export const metadata = {
    title: "Register",
    description: "Generated by create next app",
};

const RegisterPage = () => {
  return (
    <section className="min-h-screen flex items-center justify-center bg-gray-100 px-5 py-10">
      <div className="bg-white rounded-lg shadow-lg p-8 w-full max-w-xl">
        <h1 className="text-3xl font-bold text-neutral-600 mb-6 text-center">
          Create New Account
        </h1>
        <RegisterForm />
      </div>
    </section>
  )
}

export default RegisterPage